### ISSUE TITLE
这个链接失效了啊

### ISSUE THREAD

**Issue by lexiaoyao20** [lefex/iWeChat#2]
本工具基于 python 写的，在[这里](https://github.com/lefex/WeChatShot/podlib/source)可以找到源码。下载源码后修改 file_catagory.py 文件的 IPA_HEADER_PATH 为 class-dump 导出的头文件目录

上面工具的链接失效了

**Comment by lefex** [comment]
那就在项目目录里能找到发自我的iPhone------------------ 原始邮件 ------------------发件人: lexiaoyao20  <notifications@github.com>发送时间: 2018年11月6日 20:51收件人: lefex/iWeChat <iWeChat@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[lefex/iWeChat] 这个链接失效了啊 (#2)本工具基于 python 写的，在这里可以找到源码。下载源码后修改 file_catagory.py 文件的 IPA_HEADER_PATH 为 class-dump 导出的头文件目录
上面工具的链接失效了

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lefex/iWeChat","title":"lefex/iWeChat","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/lefex/iWeChat"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"这个链接失效了啊 (#2)"}],"action":{"name":"View Issue","url":"https://github.com/lefex/iWeChat/issues/2"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lefex/iWeChat/issues/2",
"url": "https://github.com/lefex/iWeChat/issues/2",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "这个链接失效了啊 (#2)",
"sections": [
{
"text": "",
"activityTitle": "**lexiaoyao20**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@lexiaoyao20",
"facts": [
{
"name": "Repository: ",
"value": "lefex/iWeChat"
},
{
"name": "Issue #: ",
"value": 2
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"lefex/iWeChat\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"lefex/iWeChat\",\n\"issueId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/lefex/iWeChat/issues/2"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 406947938\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by lefex** [comment]
已修改
